version: "3.7"

volumes:
  postgres_data:

services:
  postgres:
    container_name: django-starter-postgres
    image: postgres:12
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev
  django-project:
    container_name: django-starter
    depends_on:
      - postgres
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./project/:/project/
      - ./main/:/main/
      - ./img/:/img/
    env_file:
      - .env.dev
  nginx:
    container_name: django-starter-nginx
    image: nginx:1.19.0-alpine
    ports:
      - "8020:80"
    volumes:
      - ./static:/code/static
      - ./media:/code/media
      - ./nginx:/etc/nginx/conf.d/
    depends_on:
      - django-project
    restart: always
